spring:
  application:
    name: email-llm-integration
  datasource:
    url: jdbc:sqlite:${SQLITE_DB_PATH:/data/emails.db}
    driver-class-name: org.sqlite.JDBC
  mail:
    host: ${EMAIL_HOST:test-smtp.example.com}
    port: ${EMAIL_PORT:587}
    username: ${EMAIL_USER:test@example.com}
    password: ${EMAIL_PASSWORD:test_password}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: ${EMAIL_USE_TLS:true}

server:
  port: 8080
  servlet:
    context-path: /
  tomcat:
    connection-timeout: 20000
    max-threads: 100
    min-spare-threads: 10
    accesslog:
      enabled: true
      directory: /logs
      pattern: '%t %a "%r" %s %b %D ms'

# Camel configuration
camel:
  springboot:
    name: Email-LLM-Integration
    main-run-controller: true
    jmx-enabled: false
  component:
    servlet:
      mapping:
        context-path: /api/*
    http:
      connection-request-timeout: 30000
      connection-timeout: 30000
      socket-timeout: 60000
  dataformat:
    json:
      library: jackson
  routes:
    include-pattern: classpath:routes/*.groovy
    reload-directory: ${CAMEL_ROUTES_RELOAD_DIRECTORY:/app/routes}
  stream:
    cache:
      enabled: ${CAMEL_STREAM_CACHE_ENABLED:true}

# Actuator endpoints
management:
  endpoints:
    web:
      exposure:
        include: health,info,camelroutes,metrics
  endpoint:
    health:
      show-details: always
    camelroutes:
      enabled: true
      read-only: false

# Logging configuration
logging:
  level:
    root: ${LOG_LEVEL:INFO}
    com.example.emailllm: ${LOG_LEVEL:DEBUG}
    org.apache.camel: ${CAMEL_DEBUG:INFO}
  file:
    name: /logs/application.log
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} - %msg%n"
    file: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"

# Ollama LLM configuration
ollama:
  host: ${OLLAMA_HOST:ollama}
  port: ${OLLAMA_PORT:11434}
  model: ${OLLAMA_MODEL:mistral}
  timeout: 60000